//! Characterization of the cook path across the pipeline port.
//!
//! Expected values were captured from the pre-pipeline `cook_post` /
//! `cook_individual_post` implementation over a matrix of list settings,
//! message shapes and consumers. Headers are compared as a sorted multiset of
//! `(lowercased name, unfolded value)` because handler order now decides
//! emission order; bodies are compared byte for byte.
//!
//! Two deliberate differences from the capture are encoded here rather than
//! absorbed silently: the archive copy now carries the full `X-BeenThere`
//! loop history like the delivery and digest copies (it used to record only
//! the posting address), and the DMARC-munged `From`/`Reply-To` now follow
//! the `List-*` headers because the `dmarc` handler runs after `rfc-2369`.
//! The headers the completed `cook-headers`/`rfc-2369` handlers add on top
//! of the capture (`ADDED_SINCE_CAPTURE`) are ignored here and pinned by
//! `tests/cook_headers.rs`.
use listmngr_core::{DmarcMitigateAction, MailingList};
use listmngr_mail::handlers::{Target, cook_for};

fn list(kind: &str) -> MailingList {
    let mut list = MailingList::new("dev.example.invalid".parse().unwrap(), "Dev".into());
    match kind {
        "plain" => {}
        "anonymous" => list.anonymous_list = true,
        "munge" => {
            list.dmarc.action = DmarcMitigateAction::MungeFrom;
            list.dmarc.unconditional = true;
        }
        "unicode" => list.subject_prefix = "[Việt] ".into(),
        _ => unreachable!(),
    }
    list
}

const FULL: &str = "From: Alice <alice@example.invalid>\r\nTo: dev@example.invalid\r\nCc: bob@example.invalid\r\nSubject: Release notes\r\nMessage-ID: <m1@example.invalid>\r\nDate: Mon, 1 Sep 2026 10:00:00 +0000\r\nList-Post: <mailto:other@example.invalid>\r\nX-BeenThere: older@example.invalid\r\nDKIM-Signature: v=1; d=example.invalid; s=k\r\nARC-Seal: i=1\r\nBcc: hidden@example.invalid\r\nPrecedence: bulk\r\nApproved: s3cret\r\nReply-To: alice-alt@example.invalid\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=utf-8\r\n\r\nApproved: s3cret\r\nHello list\r\n-- \r\nsig\r\n";

fn message(name: &str) -> Vec<u8> {
    match name {
        "crlf-full" => FULL.as_bytes().to_vec(),
        "lf-full" => FULL.replace("\r\n", "\n").into_bytes(),
        "no-subject" => b"From: alice@example.invalid\r\nTo: dev@example.invalid\r\nMessage-ID: <m2@example.invalid>\r\n\r\nbody\r\n".to_vec(),
        "prefixed" => b"From: alice@example.invalid\r\nTo: dev@example.invalid\r\nSubject: [dev] already\r\nMessage-ID: <m3@example.invalid>\r\n\r\nbody\r\n".to_vec(),
        "unicode-subject" => "From: alice@example.invalid\r\nTo: dev@example.invalid\r\nSubject: Xin ch\u{e0}o\r\nMessage-ID: <m4@example.invalid>\r\n\r\nbody\r\n".as_bytes().to_vec(),
        _ => unreachable!(),
    }
}

/// Headers the completed handlers add that the capture predates.
const ADDED_SINCE_CAPTURE: &[&str] = &[
    "sender",
    "x-mailman-version",
    "message-id-hash",
    "x-message-id-hash",
    "list-help",
    "list-owner",
];

/// Sorted `(name, value)` header multiset and the exact body bytes.
fn shape(cooked: &[u8]) -> (Vec<(String, String)>, Vec<u8>) {
    let (blank, body) = listmngr_mail::header_body_split(cooked).expect("cooked boundary");
    let mut headers: Vec<(String, String)> = listmngr_mail::facts::header_fields(&cooked[..blank])
        .into_iter()
        .map(|(name, value)| (name.to_ascii_lowercase(), value))
        .filter(|(name, _)| !ADDED_SINCE_CAPTURE.contains(&name.as_str()))
        .collect();
    headers.sort();
    (headers, cooked[body..].to_vec())
}

struct Case {
    list: &'static str,
    message: &'static str,
    target: Target,
    headers: &'static [(&'static str, &'static str)],
    body: &'static str,
}

fn check(case: &Case) {
    let list = list(case.list);
    let raw = message(case.message);
    let label = format!("{} / {} / {:?}", case.list, case.message, case.target);
    let bytes = cook_for(case.target, &raw, &list, "identity")
        .unwrap_or_else(|error| panic!("{label}: unexpected error {error}"));
    let (actual_headers, actual_body) = shape(&bytes);
    let expected_headers: Vec<(String, String)> = case
        .headers
        .iter()
        .map(|(name, value)| ((*name).to_owned(), (*value).to_owned()))
        .collect();
    assert_eq!(actual_headers, expected_headers, "{label}: headers");
    assert_eq!(actual_body, case.body.as_bytes(), "{label}: body");
}

static PLAIN_CASES: &[Case] = &[
    Case {
        list: "plain",
        message: "crlf-full",
        target: Target::Out,
        headers: &[
            ("cc", "bob@example.invalid"),
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "Alice <alice@example.invalid>"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m1@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "alice-alt@example.invalid"),
            ("subject", "[dev] Release notes"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\r\n-- \r\nsig\r\n",
    },
    Case {
        list: "plain",
        message: "crlf-full",
        target: Target::Archive,
        headers: &[
            ("cc", "bob@example.invalid"),
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "Alice <alice@example.invalid>"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m1@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "alice-alt@example.invalid"),
            ("subject", "[dev] Release notes"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\r\n-- \r\nsig\r\n",
    },
    Case {
        list: "plain",
        message: "crlf-full",
        target: Target::Digest,
        headers: &[
            ("cc", "bob@example.invalid"),
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "Alice <alice@example.invalid>"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m1@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "alice-alt@example.invalid"),
            ("subject", "[dev] Release notes"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\r\n-- \r\nsig\r\n",
    },
    Case {
        list: "plain",
        message: "lf-full",
        target: Target::Out,
        headers: &[
            ("cc", "bob@example.invalid"),
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "Alice <alice@example.invalid>"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m1@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "alice-alt@example.invalid"),
            ("subject", "[dev] Release notes"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\n-- \nsig\n",
    },
    Case {
        list: "plain",
        message: "lf-full",
        target: Target::Archive,
        headers: &[
            ("cc", "bob@example.invalid"),
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "Alice <alice@example.invalid>"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m1@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "alice-alt@example.invalid"),
            ("subject", "[dev] Release notes"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\n-- \nsig\n",
    },
    Case {
        list: "plain",
        message: "lf-full",
        target: Target::Digest,
        headers: &[
            ("cc", "bob@example.invalid"),
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "Alice <alice@example.invalid>"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m1@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "alice-alt@example.invalid"),
            ("subject", "[dev] Release notes"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\n-- \nsig\n",
    },
    Case {
        list: "plain",
        message: "no-subject",
        target: Target::Out,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m2@example.invalid>"),
            ("precedence", "list"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "plain",
        message: "no-subject",
        target: Target::Archive,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m2@example.invalid>"),
            ("precedence", "list"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "plain",
        message: "no-subject",
        target: Target::Digest,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m2@example.invalid>"),
            ("precedence", "list"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "plain",
        message: "prefixed",
        target: Target::Out,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m3@example.invalid>"),
            ("precedence", "list"),
            ("subject", "[dev] already"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "plain",
        message: "prefixed",
        target: Target::Archive,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m3@example.invalid>"),
            ("precedence", "list"),
            ("subject", "[dev] already"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "plain",
        message: "prefixed",
        target: Target::Digest,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m3@example.invalid>"),
            ("precedence", "list"),
            ("subject", "[dev] already"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "plain",
        message: "unicode-subject",
        target: Target::Out,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m4@example.invalid>"),
            ("precedence", "list"),
            ("subject", "[dev] Xin ch\u{00e0}o"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "plain",
        message: "unicode-subject",
        target: Target::Archive,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m4@example.invalid>"),
            ("precedence", "list"),
            ("subject", "[dev] Xin ch\u{00e0}o"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "plain",
        message: "unicode-subject",
        target: Target::Digest,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m4@example.invalid>"),
            ("precedence", "list"),
            ("subject", "[dev] Xin ch\u{00e0}o"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
];

#[test]
fn plain_list_matches_the_captured_cook_shape() {
    for case in PLAIN_CASES {
        check(case);
    }
}

static ANONYMOUS_CASES: &[Case] = &[
    Case {
        list: "anonymous",
        message: "crlf-full",
        target: Target::Out,
        headers: &[
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "dev@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<identity@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "dev@example.invalid"),
            ("subject", "[dev] Release notes"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\r\n-- \r\nsig\r\n",
    },
    Case {
        list: "anonymous",
        message: "crlf-full",
        target: Target::Archive,
        headers: &[
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "dev@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<identity@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "dev@example.invalid"),
            ("subject", "[dev] Release notes"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\r\n-- \r\nsig\r\n",
    },
    Case {
        list: "anonymous",
        message: "crlf-full",
        target: Target::Digest,
        headers: &[
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "dev@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<identity@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "dev@example.invalid"),
            ("subject", "[dev] Release notes"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\r\n-- \r\nsig\r\n",
    },
    Case {
        list: "anonymous",
        message: "lf-full",
        target: Target::Out,
        headers: &[
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "dev@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<identity@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "dev@example.invalid"),
            ("subject", "[dev] Release notes"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\n-- \nsig\n",
    },
    Case {
        list: "anonymous",
        message: "lf-full",
        target: Target::Archive,
        headers: &[
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "dev@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<identity@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "dev@example.invalid"),
            ("subject", "[dev] Release notes"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\n-- \nsig\n",
    },
    Case {
        list: "anonymous",
        message: "lf-full",
        target: Target::Digest,
        headers: &[
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "dev@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<identity@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "dev@example.invalid"),
            ("subject", "[dev] Release notes"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\n-- \nsig\n",
    },
    Case {
        list: "anonymous",
        message: "no-subject",
        target: Target::Out,
        headers: &[
            ("from", "dev@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<identity@example.invalid>"),
            ("precedence", "list"),
            ("reply-to", "dev@example.invalid"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "anonymous",
        message: "no-subject",
        target: Target::Archive,
        headers: &[
            ("from", "dev@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<identity@example.invalid>"),
            ("precedence", "list"),
            ("reply-to", "dev@example.invalid"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "anonymous",
        message: "no-subject",
        target: Target::Digest,
        headers: &[
            ("from", "dev@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<identity@example.invalid>"),
            ("precedence", "list"),
            ("reply-to", "dev@example.invalid"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "anonymous",
        message: "prefixed",
        target: Target::Out,
        headers: &[
            ("from", "dev@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<identity@example.invalid>"),
            ("precedence", "list"),
            ("reply-to", "dev@example.invalid"),
            ("subject", "[dev] already"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "anonymous",
        message: "prefixed",
        target: Target::Archive,
        headers: &[
            ("from", "dev@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<identity@example.invalid>"),
            ("precedence", "list"),
            ("reply-to", "dev@example.invalid"),
            ("subject", "[dev] already"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "anonymous",
        message: "prefixed",
        target: Target::Digest,
        headers: &[
            ("from", "dev@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<identity@example.invalid>"),
            ("precedence", "list"),
            ("reply-to", "dev@example.invalid"),
            ("subject", "[dev] already"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "anonymous",
        message: "unicode-subject",
        target: Target::Out,
        headers: &[
            ("from", "dev@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<identity@example.invalid>"),
            ("precedence", "list"),
            ("reply-to", "dev@example.invalid"),
            ("subject", "[dev] Xin ch\u{00e0}o"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "anonymous",
        message: "unicode-subject",
        target: Target::Archive,
        headers: &[
            ("from", "dev@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<identity@example.invalid>"),
            ("precedence", "list"),
            ("reply-to", "dev@example.invalid"),
            ("subject", "[dev] Xin ch\u{00e0}o"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "anonymous",
        message: "unicode-subject",
        target: Target::Digest,
        headers: &[
            ("from", "dev@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<identity@example.invalid>"),
            ("precedence", "list"),
            ("reply-to", "dev@example.invalid"),
            ("subject", "[dev] Xin ch\u{00e0}o"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
];

#[test]
fn anonymous_list_matches_the_captured_cook_shape() {
    for case in ANONYMOUS_CASES {
        check(case);
    }
}

static MUNGE_CASES: &[Case] = &[
    Case {
        list: "munge",
        message: "crlf-full",
        target: Target::Out,
        headers: &[
            ("cc", "bob@example.invalid"),
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            (
                "from",
                "\"Alice (alice@example.invalid) via dev@example.invalid\" <dev@example.invalid>",
            ),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m1@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "<alice-alt@example.invalid>"),
            ("subject", "[dev] Release notes"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\r\n-- \r\nsig\r\n",
    },
    Case {
        list: "munge",
        message: "crlf-full",
        target: Target::Archive,
        headers: &[
            ("cc", "bob@example.invalid"),
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "Alice <alice@example.invalid>"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m1@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "alice-alt@example.invalid"),
            ("subject", "[dev] Release notes"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\r\n-- \r\nsig\r\n",
    },
    Case {
        list: "munge",
        message: "crlf-full",
        target: Target::Digest,
        headers: &[
            ("cc", "bob@example.invalid"),
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "Alice <alice@example.invalid>"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m1@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "alice-alt@example.invalid"),
            ("subject", "[dev] Release notes"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\r\n-- \r\nsig\r\n",
    },
    Case {
        list: "munge",
        message: "lf-full",
        target: Target::Out,
        headers: &[
            ("cc", "bob@example.invalid"),
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            (
                "from",
                "\"Alice (alice@example.invalid) via dev@example.invalid\" <dev@example.invalid>",
            ),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m1@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "<alice-alt@example.invalid>"),
            ("subject", "[dev] Release notes"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\n-- \nsig\n",
    },
    Case {
        list: "munge",
        message: "lf-full",
        target: Target::Archive,
        headers: &[
            ("cc", "bob@example.invalid"),
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "Alice <alice@example.invalid>"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m1@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "alice-alt@example.invalid"),
            ("subject", "[dev] Release notes"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\n-- \nsig\n",
    },
    Case {
        list: "munge",
        message: "lf-full",
        target: Target::Digest,
        headers: &[
            ("cc", "bob@example.invalid"),
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "Alice <alice@example.invalid>"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m1@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "alice-alt@example.invalid"),
            ("subject", "[dev] Release notes"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\n-- \nsig\n",
    },
    Case {
        list: "munge",
        message: "no-subject",
        target: Target::Out,
        headers: &[
            (
                "from",
                "\"alice@example.invalid via dev@example.invalid\" <dev@example.invalid>",
            ),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m2@example.invalid>"),
            ("precedence", "list"),
            ("reply-to", "<alice@example.invalid>"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "munge",
        message: "no-subject",
        target: Target::Archive,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m2@example.invalid>"),
            ("precedence", "list"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "munge",
        message: "no-subject",
        target: Target::Digest,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m2@example.invalid>"),
            ("precedence", "list"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "munge",
        message: "prefixed",
        target: Target::Out,
        headers: &[
            (
                "from",
                "\"alice@example.invalid via dev@example.invalid\" <dev@example.invalid>",
            ),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m3@example.invalid>"),
            ("precedence", "list"),
            ("reply-to", "<alice@example.invalid>"),
            ("subject", "[dev] already"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "munge",
        message: "prefixed",
        target: Target::Archive,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m3@example.invalid>"),
            ("precedence", "list"),
            ("subject", "[dev] already"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "munge",
        message: "prefixed",
        target: Target::Digest,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m3@example.invalid>"),
            ("precedence", "list"),
            ("subject", "[dev] already"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "munge",
        message: "unicode-subject",
        target: Target::Out,
        headers: &[
            (
                "from",
                "\"alice@example.invalid via dev@example.invalid\" <dev@example.invalid>",
            ),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m4@example.invalid>"),
            ("precedence", "list"),
            ("reply-to", "<alice@example.invalid>"),
            ("subject", "[dev] Xin ch\u{00e0}o"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "munge",
        message: "unicode-subject",
        target: Target::Archive,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m4@example.invalid>"),
            ("precedence", "list"),
            ("subject", "[dev] Xin ch\u{00e0}o"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "munge",
        message: "unicode-subject",
        target: Target::Digest,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m4@example.invalid>"),
            ("precedence", "list"),
            ("subject", "[dev] Xin ch\u{00e0}o"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
];

#[test]
fn munge_list_matches_the_captured_cook_shape() {
    for case in MUNGE_CASES {
        check(case);
    }
}

static UNICODE_CASES: &[Case] = &[
    Case {
        list: "unicode",
        message: "crlf-full",
        target: Target::Out,
        headers: &[
            ("cc", "bob@example.invalid"),
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "Alice <alice@example.invalid>"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m1@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "alice-alt@example.invalid"),
            ("subject", "=?utf-8?B?W1Zp4buHdF0gUmVsZWFzZSBub3Rlcw==?="),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\r\n-- \r\nsig\r\n",
    },
    Case {
        list: "unicode",
        message: "crlf-full",
        target: Target::Archive,
        headers: &[
            ("cc", "bob@example.invalid"),
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "Alice <alice@example.invalid>"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m1@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "alice-alt@example.invalid"),
            ("subject", "=?utf-8?B?W1Zp4buHdF0gUmVsZWFzZSBub3Rlcw==?="),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\r\n-- \r\nsig\r\n",
    },
    Case {
        list: "unicode",
        message: "crlf-full",
        target: Target::Digest,
        headers: &[
            ("cc", "bob@example.invalid"),
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "Alice <alice@example.invalid>"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m1@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "alice-alt@example.invalid"),
            ("subject", "=?utf-8?B?W1Zp4buHdF0gUmVsZWFzZSBub3Rlcw==?="),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\r\n-- \r\nsig\r\n",
    },
    Case {
        list: "unicode",
        message: "lf-full",
        target: Target::Out,
        headers: &[
            ("cc", "bob@example.invalid"),
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "Alice <alice@example.invalid>"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m1@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "alice-alt@example.invalid"),
            ("subject", "=?utf-8?B?W1Zp4buHdF0gUmVsZWFzZSBub3Rlcw==?="),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\n-- \nsig\n",
    },
    Case {
        list: "unicode",
        message: "lf-full",
        target: Target::Archive,
        headers: &[
            ("cc", "bob@example.invalid"),
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "Alice <alice@example.invalid>"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m1@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "alice-alt@example.invalid"),
            ("subject", "=?utf-8?B?W1Zp4buHdF0gUmVsZWFzZSBub3Rlcw==?="),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\n-- \nsig\n",
    },
    Case {
        list: "unicode",
        message: "lf-full",
        target: Target::Digest,
        headers: &[
            ("cc", "bob@example.invalid"),
            ("content-type", "text/plain; charset=utf-8"),
            ("date", "Mon, 1 Sep 2026 10:00:00 +0000"),
            ("from", "Alice <alice@example.invalid>"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m1@example.invalid>"),
            ("mime-version", "1.0"),
            ("precedence", "list"),
            ("reply-to", "alice-alt@example.invalid"),
            ("subject", "=?utf-8?B?W1Zp4buHdF0gUmVsZWFzZSBub3Rlcw==?="),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
            ("x-beenthere", "older@example.invalid"),
            ("x-beenthere", "other@example.invalid"),
        ],
        body: "Hello list\n-- \nsig\n",
    },
    Case {
        list: "unicode",
        message: "no-subject",
        target: Target::Out,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m2@example.invalid>"),
            ("precedence", "list"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "unicode",
        message: "no-subject",
        target: Target::Archive,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m2@example.invalid>"),
            ("precedence", "list"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "unicode",
        message: "no-subject",
        target: Target::Digest,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m2@example.invalid>"),
            ("precedence", "list"),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "unicode",
        message: "prefixed",
        target: Target::Out,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m3@example.invalid>"),
            ("precedence", "list"),
            ("subject", "=?utf-8?B?W1Zp4buHdF0gW2Rldl0gYWxyZWFkeQ==?="),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "unicode",
        message: "prefixed",
        target: Target::Archive,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m3@example.invalid>"),
            ("precedence", "list"),
            ("subject", "=?utf-8?B?W1Zp4buHdF0gW2Rldl0gYWxyZWFkeQ==?="),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "unicode",
        message: "prefixed",
        target: Target::Digest,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m3@example.invalid>"),
            ("precedence", "list"),
            ("subject", "=?utf-8?B?W1Zp4buHdF0gW2Rldl0gYWxyZWFkeQ==?="),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "unicode",
        message: "unicode-subject",
        target: Target::Out,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m4@example.invalid>"),
            ("precedence", "list"),
            ("subject", "=?utf-8?B?W1Zp4buHdF0gWGluIGNow6Bv?="),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "unicode",
        message: "unicode-subject",
        target: Target::Archive,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m4@example.invalid>"),
            ("precedence", "list"),
            ("subject", "=?utf-8?B?W1Zp4buHdF0gWGluIGNow6Bv?="),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
    Case {
        list: "unicode",
        message: "unicode-subject",
        target: Target::Digest,
        headers: &[
            ("from", "alice@example.invalid"),
            ("list-id", "<dev.example.invalid>"),
            ("list-post", "<mailto:dev@example.invalid>"),
            ("list-subscribe", "<mailto:dev-join@example.invalid>"),
            ("list-unsubscribe", "<mailto:dev-leave@example.invalid>"),
            ("message-id", "<m4@example.invalid>"),
            ("precedence", "list"),
            ("subject", "=?utf-8?B?W1Zp4buHdF0gWGluIGNow6Bv?="),
            ("to", "dev@example.invalid"),
            ("x-beenthere", "dev@example.invalid"),
        ],
        body: "body\r\n",
    },
];

#[test]
fn unicode_list_matches_the_captured_cook_shape() {
    for case in UNICODE_CASES {
        check(case);
    }
}
