[package]
name = "listmngr"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
chrono.workspace = true
listmngr-api = { path = "../api", version = "0.1.0" }
listmngr-core = { path = "../core", version = "0.1.0" }
listmngr-db = { path = "../db", version = "0.1.0" }
listmngr-mail = { path = "../mail", version = "0.1.0" }
listmngr-runners = { path = "../runners", version = "0.1.0" }
serde_json.workspace = true
rpassword.workspace = true
reqwest.workspace = true
sqlx = { workspace = true, features = ["any"] }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
tempfile = "3.23.0"

[dev-dependencies]
sha2.workspace = true
assert_cmd = "2.1.1"
predicates = "3.1.3"
base64.workspace = true
mail-auth = { version = "=0.12.1", default-features = false, features = ["ring"] }
