[package]
name = "listmngr-i18n"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[package.metadata.listmngr]
delivery-phase = 3

[lints]
workspace = true

[dependencies]
fluent-bundle = "=0.16.0"
intl-memoizer = "0.5.3"
unic-langid = { version = "=0.9.6", features = ["macros"] }
