apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "listmngr.fullname" . }}
  labels:
    {{- include "listmngr.labels" . | nindent 4 }}
data:
  listmngr.toml: |
{{ .Values.config | indent 4 }}
