{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "listmngr.fullname" . }}
  labels:
    {{- include "listmngr.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.secretFiles (not .Values.existingFilesSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "listmngr.fullname" . }}-files
  labels:
    {{- include "listmngr.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $content := .Values.secretFiles }}
  {{ $name }}: {{ $content | quote }}
  {{- end }}
{{- end }}
