// Generated by tests/compat/import_mailman_templates.py from GNU Mailman
// 3.3.10 (GPL-3.0-or-later translations). Do not edit.
//! Mailman's translated bodies for the templates whose English listmngr
//! keeps as Mailman wrote it; see `IMPORTED`.

/// The templates a Mailman translation may serve.
pub const IMPORTED: &[&str] = &[
    "domain:admin:notice:new-list",
    "list:admin:action:post",
    "list:admin:action:subscribe",
    "list:admin:action:unsubscribe",
    "list:admin:notice:pending",
    "list:admin:notice:removal",
    "list:admin:notice:subscribe",
    "list:admin:notice:unrecognized",
    "list:admin:notice:unsubscribe",
    "list:member:digest:header",
    "list:member:digest:masthead",
    "list:member:generic:footer",
    "list:member:regular:header",
    "list:user:notice:hold",
    "list:user:notice:no-more-today",
    "list:user:notice:post",
    "list:user:notice:refuse",
];

/// The languages with at least one translated body.
pub const LANGUAGES: &[&str] = &[
    "bg", "ca", "cs", "de", "eo", "es", "fr", "he", "hu", "id", "it", "ja", "ko", "nl", "pt",
    "pt-BR", "ru", "sk", "tr", "uk", "zh-Hans",
];

/// Mailman's English for each imported template, as vendored.
#[must_use]
#[allow(clippy::match_same_arms)] // One arm per vendored file.
pub fn english(name: &str) -> Option<&'static str> {
    Some(match name {
        "domain:admin:notice:new-list" => {
            include_str!("../catalog/mailman/en/domain:admin:notice:new-list.txt")
        }
        "list:admin:action:post" => {
            include_str!("../catalog/mailman/en/list:admin:action:post.txt")
        }
        "list:admin:action:subscribe" => {
            include_str!("../catalog/mailman/en/list:admin:action:subscribe.txt")
        }
        "list:admin:action:unsubscribe" => {
            include_str!("../catalog/mailman/en/list:admin:action:unsubscribe.txt")
        }
        "list:admin:notice:pending" => {
            include_str!("../catalog/mailman/en/list:admin:notice:pending.txt")
        }
        "list:admin:notice:removal" => {
            include_str!("../catalog/mailman/en/list:admin:notice:removal.txt")
        }
        "list:admin:notice:subscribe" => {
            include_str!("../catalog/mailman/en/list:admin:notice:subscribe.txt")
        }
        "list:admin:notice:unrecognized" => {
            include_str!("../catalog/mailman/en/list:admin:notice:unrecognized.txt")
        }
        "list:admin:notice:unsubscribe" => {
            include_str!("../catalog/mailman/en/list:admin:notice:unsubscribe.txt")
        }
        "list:member:digest:header" => {
            include_str!("../catalog/mailman/en/list:member:digest:header.txt")
        }
        "list:member:digest:masthead" => {
            include_str!("../catalog/mailman/en/list:member:digest:masthead.txt")
        }
        "list:member:generic:footer" => {
            include_str!("../catalog/mailman/en/list:member:generic:footer.txt")
        }
        "list:member:regular:header" => {
            include_str!("../catalog/mailman/en/list:member:regular:header.txt")
        }
        "list:user:notice:hold" => include_str!("../catalog/mailman/en/list:user:notice:hold.txt"),
        "list:user:notice:no-more-today" => {
            include_str!("../catalog/mailman/en/list:user:notice:no-more-today.txt")
        }
        "list:user:notice:post" => include_str!("../catalog/mailman/en/list:user:notice:post.txt"),
        "list:user:notice:refuse" => {
            include_str!("../catalog/mailman/en/list:user:notice:refuse.txt")
        }
        _ => return None,
    })
}

/// Mailman's translation of `name` into `language`, when it has one.
#[must_use]
// One arm per vendored file; some languages share a translation.
#[allow(clippy::too_many_lines, clippy::match_same_arms)]
pub fn builtin(language: &str, name: &str) -> Option<&'static str> {
    Some(match (language, name) {
        ("bg", "domain:admin:notice:new-list") => {
            include_str!("../catalog/mailman/bg/domain:admin:notice:new-list.txt")
        }
        ("bg", "list:admin:action:post") => {
            include_str!("../catalog/mailman/bg/list:admin:action:post.txt")
        }
        ("bg", "list:admin:action:subscribe") => {
            include_str!("../catalog/mailman/bg/list:admin:action:subscribe.txt")
        }
        ("bg", "list:admin:action:unsubscribe") => {
            include_str!("../catalog/mailman/bg/list:admin:action:unsubscribe.txt")
        }
        ("bg", "list:admin:notice:pending") => {
            include_str!("../catalog/mailman/bg/list:admin:notice:pending.txt")
        }
        ("bg", "list:admin:notice:removal") => {
            include_str!("../catalog/mailman/bg/list:admin:notice:removal.txt")
        }
        ("bg", "list:admin:notice:subscribe") => {
            include_str!("../catalog/mailman/bg/list:admin:notice:subscribe.txt")
        }
        ("bg", "list:admin:notice:unrecognized") => {
            include_str!("../catalog/mailman/bg/list:admin:notice:unrecognized.txt")
        }
        ("bg", "list:admin:notice:unsubscribe") => {
            include_str!("../catalog/mailman/bg/list:admin:notice:unsubscribe.txt")
        }
        ("bg", "list:member:digest:masthead") => {
            include_str!("../catalog/mailman/bg/list:member:digest:masthead.txt")
        }
        ("bg", "list:member:generic:footer") => {
            include_str!("../catalog/mailman/bg/list:member:generic:footer.txt")
        }
        ("bg", "list:user:notice:hold") => {
            include_str!("../catalog/mailman/bg/list:user:notice:hold.txt")
        }
        ("bg", "list:user:notice:no-more-today") => {
            include_str!("../catalog/mailman/bg/list:user:notice:no-more-today.txt")
        }
        ("bg", "list:user:notice:post") => {
            include_str!("../catalog/mailman/bg/list:user:notice:post.txt")
        }
        ("bg", "list:user:notice:refuse") => {
            include_str!("../catalog/mailman/bg/list:user:notice:refuse.txt")
        }
        ("ca", "domain:admin:notice:new-list") => {
            include_str!("../catalog/mailman/ca/domain:admin:notice:new-list.txt")
        }
        ("ca", "list:admin:action:post") => {
            include_str!("../catalog/mailman/ca/list:admin:action:post.txt")
        }
        ("ca", "list:admin:action:subscribe") => {
            include_str!("../catalog/mailman/ca/list:admin:action:subscribe.txt")
        }
        ("ca", "list:admin:action:unsubscribe") => {
            include_str!("../catalog/mailman/ca/list:admin:action:unsubscribe.txt")
        }
        ("ca", "list:admin:notice:subscribe") => {
            include_str!("../catalog/mailman/ca/list:admin:notice:subscribe.txt")
        }
        ("ca", "list:admin:notice:unrecognized") => {
            include_str!("../catalog/mailman/ca/list:admin:notice:unrecognized.txt")
        }
        ("ca", "list:admin:notice:unsubscribe") => {
            include_str!("../catalog/mailman/ca/list:admin:notice:unsubscribe.txt")
        }
        ("ca", "list:member:generic:footer") => {
            include_str!("../catalog/mailman/ca/list:member:generic:footer.txt")
        }
        ("ca", "list:user:notice:hold") => {
            include_str!("../catalog/mailman/ca/list:user:notice:hold.txt")
        }
        ("ca", "list:user:notice:no-more-today") => {
            include_str!("../catalog/mailman/ca/list:user:notice:no-more-today.txt")
        }
        ("cs", "domain:admin:notice:new-list") => {
            include_str!("../catalog/mailman/cs/domain:admin:notice:new-list.txt")
        }
        ("cs", "list:admin:action:post") => {
            include_str!("../catalog/mailman/cs/list:admin:action:post.txt")
        }
        ("cs", "list:admin:action:subscribe") => {
            include_str!("../catalog/mailman/cs/list:admin:action:subscribe.txt")
        }
        ("cs", "list:admin:action:unsubscribe") => {
            include_str!("../catalog/mailman/cs/list:admin:action:unsubscribe.txt")
        }
        ("cs", "list:admin:notice:pending") => {
            include_str!("../catalog/mailman/cs/list:admin:notice:pending.txt")
        }
        ("cs", "list:admin:notice:removal") => {
            include_str!("../catalog/mailman/cs/list:admin:notice:removal.txt")
        }
        ("cs", "list:admin:notice:subscribe") => {
            include_str!("../catalog/mailman/cs/list:admin:notice:subscribe.txt")
        }
        ("cs", "list:admin:notice:unrecognized") => {
            include_str!("../catalog/mailman/cs/list:admin:notice:unrecognized.txt")
        }
        ("cs", "list:admin:notice:unsubscribe") => {
            include_str!("../catalog/mailman/cs/list:admin:notice:unsubscribe.txt")
        }
        ("cs", "list:member:digest:masthead") => {
            include_str!("../catalog/mailman/cs/list:member:digest:masthead.txt")
        }
        ("cs", "list:member:generic:footer") => {
            include_str!("../catalog/mailman/cs/list:member:generic:footer.txt")
        }
        ("cs", "list:user:notice:hold") => {
            include_str!("../catalog/mailman/cs/list:user:notice:hold.txt")
        }
        ("cs", "list:user:notice:no-more-today") => {
            include_str!("../catalog/mailman/cs/list:user:notice:no-more-today.txt")
        }
        ("cs", "list:user:notice:post") => {
            include_str!("../catalog/mailman/cs/list:user:notice:post.txt")
        }
        ("de", "domain:admin:notice:new-list") => {
            include_str!("../catalog/mailman/de/domain:admin:notice:new-list.txt")
        }
        ("de", "list:admin:action:post") => {
            include_str!("../catalog/mailman/de/list:admin:action:post.txt")
        }
        ("de", "list:admin:action:subscribe") => {
            include_str!("../catalog/mailman/de/list:admin:action:subscribe.txt")
        }
        ("de", "list:admin:action:unsubscribe") => {
            include_str!("../catalog/mailman/de/list:admin:action:unsubscribe.txt")
        }
        ("de", "list:admin:notice:pending") => {
            include_str!("../catalog/mailman/de/list:admin:notice:pending.txt")
        }
        ("de", "list:admin:notice:removal") => {
            include_str!("../catalog/mailman/de/list:admin:notice:removal.txt")
        }
        ("de", "list:admin:notice:subscribe") => {
            include_str!("../catalog/mailman/de/list:admin:notice:subscribe.txt")
        }
        ("de", "list:admin:notice:unrecognized") => {
            include_str!("../catalog/mailman/de/list:admin:notice:unrecognized.txt")
        }
        ("de", "list:admin:notice:unsubscribe") => {
            include_str!("../catalog/mailman/de/list:admin:notice:unsubscribe.txt")
        }
        ("de", "list:member:digest:masthead") => {
            include_str!("../catalog/mailman/de/list:member:digest:masthead.txt")
        }
        ("de", "list:member:generic:footer") => {
            include_str!("../catalog/mailman/de/list:member:generic:footer.txt")
        }
        ("de", "list:user:notice:hold") => {
            include_str!("../catalog/mailman/de/list:user:notice:hold.txt")
        }
        ("de", "list:user:notice:no-more-today") => {
            include_str!("../catalog/mailman/de/list:user:notice:no-more-today.txt")
        }
        ("de", "list:user:notice:post") => {
            include_str!("../catalog/mailman/de/list:user:notice:post.txt")
        }
        ("de", "list:user:notice:refuse") => {
            include_str!("../catalog/mailman/de/list:user:notice:refuse.txt")
        }
        ("eo", "list:admin:notice:subscribe") => {
            include_str!("../catalog/mailman/eo/list:admin:notice:subscribe.txt")
        }
        ("eo", "list:member:generic:footer") => {
            include_str!("../catalog/mailman/eo/list:member:generic:footer.txt")
        }
        ("eo", "list:user:notice:post") => {
            include_str!("../catalog/mailman/eo/list:user:notice:post.txt")
        }
        ("es", "domain:admin:notice:new-list") => {
            include_str!("../catalog/mailman/es/domain:admin:notice:new-list.txt")
        }
        ("es", "list:admin:action:post") => {
            include_str!("../catalog/mailman/es/list:admin:action:post.txt")
        }
        ("es", "list:admin:action:subscribe") => {
            include_str!("../catalog/mailman/es/list:admin:action:subscribe.txt")
        }
        ("es", "list:admin:action:unsubscribe") => {
            include_str!("../catalog/mailman/es/list:admin:action:unsubscribe.txt")
        }
        ("es", "list:admin:notice:pending") => {
            include_str!("../catalog/mailman/es/list:admin:notice:pending.txt")
        }
        ("es", "list:admin:notice:subscribe") => {
            include_str!("../catalog/mailman/es/list:admin:notice:subscribe.txt")
        }
        ("es", "list:admin:notice:unrecognized") => {
            include_str!("../catalog/mailman/es/list:admin:notice:unrecognized.txt")
        }
        ("es", "list:admin:notice:unsubscribe") => {
            include_str!("../catalog/mailman/es/list:admin:notice:unsubscribe.txt")
        }
        ("es", "list:member:digest:masthead") => {
            include_str!("../catalog/mailman/es/list:member:digest:masthead.txt")
        }
        ("es", "list:member:generic:footer") => {
            include_str!("../catalog/mailman/es/list:member:generic:footer.txt")
        }
        ("es", "list:user:notice:hold") => {
            include_str!("../catalog/mailman/es/list:user:notice:hold.txt")
        }
        ("es", "list:user:notice:no-more-today") => {
            include_str!("../catalog/mailman/es/list:user:notice:no-more-today.txt")
        }
        ("es", "list:user:notice:post") => {
            include_str!("../catalog/mailman/es/list:user:notice:post.txt")
        }
        ("es", "list:user:notice:refuse") => {
            include_str!("../catalog/mailman/es/list:user:notice:refuse.txt")
        }
        ("fr", "domain:admin:notice:new-list") => {
            include_str!("../catalog/mailman/fr/domain:admin:notice:new-list.txt")
        }
        ("fr", "list:admin:action:post") => {
            include_str!("../catalog/mailman/fr/list:admin:action:post.txt")
        }
        ("fr", "list:admin:action:subscribe") => {
            include_str!("../catalog/mailman/fr/list:admin:action:subscribe.txt")
        }
        ("fr", "list:admin:action:unsubscribe") => {
            include_str!("../catalog/mailman/fr/list:admin:action:unsubscribe.txt")
        }
        ("fr", "list:admin:notice:pending") => {
            include_str!("../catalog/mailman/fr/list:admin:notice:pending.txt")
        }
        ("fr", "list:admin:notice:removal") => {
            include_str!("../catalog/mailman/fr/list:admin:notice:removal.txt")
        }
        ("fr", "list:admin:notice:subscribe") => {
            include_str!("../catalog/mailman/fr/list:admin:notice:subscribe.txt")
        }
        ("fr", "list:admin:notice:unrecognized") => {
            include_str!("../catalog/mailman/fr/list:admin:notice:unrecognized.txt")
        }
        ("fr", "list:admin:notice:unsubscribe") => {
            include_str!("../catalog/mailman/fr/list:admin:notice:unsubscribe.txt")
        }
        ("fr", "list:member:digest:masthead") => {
            include_str!("../catalog/mailman/fr/list:member:digest:masthead.txt")
        }
        ("fr", "list:member:generic:footer") => {
            include_str!("../catalog/mailman/fr/list:member:generic:footer.txt")
        }
        ("fr", "list:user:notice:hold") => {
            include_str!("../catalog/mailman/fr/list:user:notice:hold.txt")
        }
        ("fr", "list:user:notice:no-more-today") => {
            include_str!("../catalog/mailman/fr/list:user:notice:no-more-today.txt")
        }
        ("fr", "list:user:notice:post") => {
            include_str!("../catalog/mailman/fr/list:user:notice:post.txt")
        }
        ("fr", "list:user:notice:refuse") => {
            include_str!("../catalog/mailman/fr/list:user:notice:refuse.txt")
        }
        ("he", "domain:admin:notice:new-list") => {
            include_str!("../catalog/mailman/he/domain:admin:notice:new-list.txt")
        }
        ("he", "list:admin:action:post") => {
            include_str!("../catalog/mailman/he/list:admin:action:post.txt")
        }
        ("he", "list:admin:action:subscribe") => {
            include_str!("../catalog/mailman/he/list:admin:action:subscribe.txt")
        }
        ("he", "list:admin:action:unsubscribe") => {
            include_str!("../catalog/mailman/he/list:admin:action:unsubscribe.txt")
        }
        ("he", "list:admin:notice:pending") => {
            include_str!("../catalog/mailman/he/list:admin:notice:pending.txt")
        }
        ("he", "list:admin:notice:removal") => {
            include_str!("../catalog/mailman/he/list:admin:notice:removal.txt")
        }
        ("he", "list:admin:notice:subscribe") => {
            include_str!("../catalog/mailman/he/list:admin:notice:subscribe.txt")
        }
        ("he", "list:admin:notice:unrecognized") => {
            include_str!("../catalog/mailman/he/list:admin:notice:unrecognized.txt")
        }
        ("he", "list:admin:notice:unsubscribe") => {
            include_str!("../catalog/mailman/he/list:admin:notice:unsubscribe.txt")
        }
        ("he", "list:member:digest:masthead") => {
            include_str!("../catalog/mailman/he/list:member:digest:masthead.txt")
        }
        ("he", "list:member:generic:footer") => {
            include_str!("../catalog/mailman/he/list:member:generic:footer.txt")
        }
        ("he", "list:user:notice:hold") => {
            include_str!("../catalog/mailman/he/list:user:notice:hold.txt")
        }
        ("he", "list:user:notice:no-more-today") => {
            include_str!("../catalog/mailman/he/list:user:notice:no-more-today.txt")
        }
        ("he", "list:user:notice:post") => {
            include_str!("../catalog/mailman/he/list:user:notice:post.txt")
        }
        ("he", "list:user:notice:refuse") => {
            include_str!("../catalog/mailman/he/list:user:notice:refuse.txt")
        }
        ("hu", "list:admin:notice:removal") => {
            include_str!("../catalog/mailman/hu/list:admin:notice:removal.txt")
        }
        ("id", "domain:admin:notice:new-list") => {
            include_str!("../catalog/mailman/id/domain:admin:notice:new-list.txt")
        }
        ("id", "list:admin:action:post") => {
            include_str!("../catalog/mailman/id/list:admin:action:post.txt")
        }
        ("id", "list:admin:action:subscribe") => {
            include_str!("../catalog/mailman/id/list:admin:action:subscribe.txt")
        }
        ("id", "list:admin:action:unsubscribe") => {
            include_str!("../catalog/mailman/id/list:admin:action:unsubscribe.txt")
        }
        ("id", "list:admin:notice:removal") => {
            include_str!("../catalog/mailman/id/list:admin:notice:removal.txt")
        }
        ("id", "list:admin:notice:subscribe") => {
            include_str!("../catalog/mailman/id/list:admin:notice:subscribe.txt")
        }
        ("id", "list:admin:notice:unrecognized") => {
            include_str!("../catalog/mailman/id/list:admin:notice:unrecognized.txt")
        }
        ("id", "list:admin:notice:unsubscribe") => {
            include_str!("../catalog/mailman/id/list:admin:notice:unsubscribe.txt")
        }
        ("id", "list:member:digest:masthead") => {
            include_str!("../catalog/mailman/id/list:member:digest:masthead.txt")
        }
        ("id", "list:member:generic:footer") => {
            include_str!("../catalog/mailman/id/list:member:generic:footer.txt")
        }
        ("id", "list:user:notice:hold") => {
            include_str!("../catalog/mailman/id/list:user:notice:hold.txt")
        }
        ("id", "list:user:notice:post") => {
            include_str!("../catalog/mailman/id/list:user:notice:post.txt")
        }
        ("id", "list:user:notice:refuse") => {
            include_str!("../catalog/mailman/id/list:user:notice:refuse.txt")
        }
        ("it", "domain:admin:notice:new-list") => {
            include_str!("../catalog/mailman/it/domain:admin:notice:new-list.txt")
        }
        ("it", "list:admin:action:post") => {
            include_str!("../catalog/mailman/it/list:admin:action:post.txt")
        }
        ("it", "list:admin:action:subscribe") => {
            include_str!("../catalog/mailman/it/list:admin:action:subscribe.txt")
        }
        ("it", "list:admin:action:unsubscribe") => {
            include_str!("../catalog/mailman/it/list:admin:action:unsubscribe.txt")
        }
        ("it", "list:admin:notice:removal") => {
            include_str!("../catalog/mailman/it/list:admin:notice:removal.txt")
        }
        ("it", "list:admin:notice:subscribe") => {
            include_str!("../catalog/mailman/it/list:admin:notice:subscribe.txt")
        }
        ("it", "list:admin:notice:unrecognized") => {
            include_str!("../catalog/mailman/it/list:admin:notice:unrecognized.txt")
        }
        ("it", "list:admin:notice:unsubscribe") => {
            include_str!("../catalog/mailman/it/list:admin:notice:unsubscribe.txt")
        }
        ("it", "list:member:digest:masthead") => {
            include_str!("../catalog/mailman/it/list:member:digest:masthead.txt")
        }
        ("it", "list:member:generic:footer") => {
            include_str!("../catalog/mailman/it/list:member:generic:footer.txt")
        }
        ("it", "list:user:notice:hold") => {
            include_str!("../catalog/mailman/it/list:user:notice:hold.txt")
        }
        ("it", "list:user:notice:no-more-today") => {
            include_str!("../catalog/mailman/it/list:user:notice:no-more-today.txt")
        }
        ("it", "list:user:notice:post") => {
            include_str!("../catalog/mailman/it/list:user:notice:post.txt")
        }
        ("it", "list:user:notice:refuse") => {
            include_str!("../catalog/mailman/it/list:user:notice:refuse.txt")
        }
        ("ja", "domain:admin:notice:new-list") => {
            include_str!("../catalog/mailman/ja/domain:admin:notice:new-list.txt")
        }
        ("ja", "list:admin:action:post") => {
            include_str!("../catalog/mailman/ja/list:admin:action:post.txt")
        }
        ("ja", "list:admin:action:subscribe") => {
            include_str!("../catalog/mailman/ja/list:admin:action:subscribe.txt")
        }
        ("ja", "list:admin:action:unsubscribe") => {
            include_str!("../catalog/mailman/ja/list:admin:action:unsubscribe.txt")
        }
        ("ja", "list:admin:notice:pending") => {
            include_str!("../catalog/mailman/ja/list:admin:notice:pending.txt")
        }
        ("ja", "list:admin:notice:removal") => {
            include_str!("../catalog/mailman/ja/list:admin:notice:removal.txt")
        }
        ("ja", "list:admin:notice:subscribe") => {
            include_str!("../catalog/mailman/ja/list:admin:notice:subscribe.txt")
        }
        ("ja", "list:admin:notice:unrecognized") => {
            include_str!("../catalog/mailman/ja/list:admin:notice:unrecognized.txt")
        }
        ("ja", "list:admin:notice:unsubscribe") => {
            include_str!("../catalog/mailman/ja/list:admin:notice:unsubscribe.txt")
        }
        ("ja", "list:member:digest:masthead") => {
            include_str!("../catalog/mailman/ja/list:member:digest:masthead.txt")
        }
        ("ja", "list:member:generic:footer") => {
            include_str!("../catalog/mailman/ja/list:member:generic:footer.txt")
        }
        ("ja", "list:user:notice:hold") => {
            include_str!("../catalog/mailman/ja/list:user:notice:hold.txt")
        }
        ("ja", "list:user:notice:no-more-today") => {
            include_str!("../catalog/mailman/ja/list:user:notice:no-more-today.txt")
        }
        ("ja", "list:user:notice:post") => {
            include_str!("../catalog/mailman/ja/list:user:notice:post.txt")
        }
        ("ja", "list:user:notice:refuse") => {
            include_str!("../catalog/mailman/ja/list:user:notice:refuse.txt")
        }
        ("ko", "domain:admin:notice:new-list") => {
            include_str!("../catalog/mailman/ko/domain:admin:notice:new-list.txt")
        }
        ("ko", "list:admin:action:post") => {
            include_str!("../catalog/mailman/ko/list:admin:action:post.txt")
        }
        ("ko", "list:admin:action:subscribe") => {
            include_str!("../catalog/mailman/ko/list:admin:action:subscribe.txt")
        }
        ("ko", "list:admin:action:unsubscribe") => {
            include_str!("../catalog/mailman/ko/list:admin:action:unsubscribe.txt")
        }
        ("ko", "list:admin:notice:subscribe") => {
            include_str!("../catalog/mailman/ko/list:admin:notice:subscribe.txt")
        }
        ("ko", "list:admin:notice:unrecognized") => {
            include_str!("../catalog/mailman/ko/list:admin:notice:unrecognized.txt")
        }
        ("ko", "list:admin:notice:unsubscribe") => {
            include_str!("../catalog/mailman/ko/list:admin:notice:unsubscribe.txt")
        }
        ("ko", "list:member:digest:masthead") => {
            include_str!("../catalog/mailman/ko/list:member:digest:masthead.txt")
        }
        ("ko", "list:member:generic:footer") => {
            include_str!("../catalog/mailman/ko/list:member:generic:footer.txt")
        }
        ("ko", "list:user:notice:hold") => {
            include_str!("../catalog/mailman/ko/list:user:notice:hold.txt")
        }
        ("ko", "list:user:notice:no-more-today") => {
            include_str!("../catalog/mailman/ko/list:user:notice:no-more-today.txt")
        }
        ("ko", "list:user:notice:post") => {
            include_str!("../catalog/mailman/ko/list:user:notice:post.txt")
        }
        ("ko", "list:user:notice:refuse") => {
            include_str!("../catalog/mailman/ko/list:user:notice:refuse.txt")
        }
        ("nl", "domain:admin:notice:new-list") => {
            include_str!("../catalog/mailman/nl/domain:admin:notice:new-list.txt")
        }
        ("nl", "list:admin:action:post") => {
            include_str!("../catalog/mailman/nl/list:admin:action:post.txt")
        }
        ("nl", "list:admin:action:subscribe") => {
            include_str!("../catalog/mailman/nl/list:admin:action:subscribe.txt")
        }
        ("nl", "list:admin:action:unsubscribe") => {
            include_str!("../catalog/mailman/nl/list:admin:action:unsubscribe.txt")
        }
        ("nl", "list:admin:notice:pending") => {
            include_str!("../catalog/mailman/nl/list:admin:notice:pending.txt")
        }
        ("nl", "list:admin:notice:removal") => {
            include_str!("../catalog/mailman/nl/list:admin:notice:removal.txt")
        }
        ("nl", "list:admin:notice:subscribe") => {
            include_str!("../catalog/mailman/nl/list:admin:notice:subscribe.txt")
        }
        ("nl", "list:admin:notice:unrecognized") => {
            include_str!("../catalog/mailman/nl/list:admin:notice:unrecognized.txt")
        }
        ("nl", "list:admin:notice:unsubscribe") => {
            include_str!("../catalog/mailman/nl/list:admin:notice:unsubscribe.txt")
        }
        ("nl", "list:member:digest:masthead") => {
            include_str!("../catalog/mailman/nl/list:member:digest:masthead.txt")
        }
        ("nl", "list:member:generic:footer") => {
            include_str!("../catalog/mailman/nl/list:member:generic:footer.txt")
        }
        ("nl", "list:user:notice:hold") => {
            include_str!("../catalog/mailman/nl/list:user:notice:hold.txt")
        }
        ("nl", "list:user:notice:no-more-today") => {
            include_str!("../catalog/mailman/nl/list:user:notice:no-more-today.txt")
        }
        ("nl", "list:user:notice:post") => {
            include_str!("../catalog/mailman/nl/list:user:notice:post.txt")
        }
        ("nl", "list:user:notice:refuse") => {
            include_str!("../catalog/mailman/nl/list:user:notice:refuse.txt")
        }
        ("pt", "domain:admin:notice:new-list") => {
            include_str!("../catalog/mailman/pt/domain:admin:notice:new-list.txt")
        }
        ("pt", "list:admin:action:post") => {
            include_str!("../catalog/mailman/pt/list:admin:action:post.txt")
        }
        ("pt", "list:admin:action:subscribe") => {
            include_str!("../catalog/mailman/pt/list:admin:action:subscribe.txt")
        }
        ("pt", "list:admin:action:unsubscribe") => {
            include_str!("../catalog/mailman/pt/list:admin:action:unsubscribe.txt")
        }
        ("pt", "list:admin:notice:removal") => {
            include_str!("../catalog/mailman/pt/list:admin:notice:removal.txt")
        }
        ("pt", "list:admin:notice:subscribe") => {
            include_str!("../catalog/mailman/pt/list:admin:notice:subscribe.txt")
        }
        ("pt", "list:admin:notice:unrecognized") => {
            include_str!("../catalog/mailman/pt/list:admin:notice:unrecognized.txt")
        }
        ("pt", "list:admin:notice:unsubscribe") => {
            include_str!("../catalog/mailman/pt/list:admin:notice:unsubscribe.txt")
        }
        ("pt", "list:member:digest:masthead") => {
            include_str!("../catalog/mailman/pt/list:member:digest:masthead.txt")
        }
        ("pt", "list:member:generic:footer") => {
            include_str!("../catalog/mailman/pt/list:member:generic:footer.txt")
        }
        ("pt", "list:user:notice:hold") => {
            include_str!("../catalog/mailman/pt/list:user:notice:hold.txt")
        }
        ("pt", "list:user:notice:no-more-today") => {
            include_str!("../catalog/mailman/pt/list:user:notice:no-more-today.txt")
        }
        ("pt", "list:user:notice:post") => {
            include_str!("../catalog/mailman/pt/list:user:notice:post.txt")
        }
        ("pt", "list:user:notice:refuse") => {
            include_str!("../catalog/mailman/pt/list:user:notice:refuse.txt")
        }
        ("pt-BR", "domain:admin:notice:new-list") => {
            include_str!("../catalog/mailman/pt-BR/domain:admin:notice:new-list.txt")
        }
        ("pt-BR", "list:admin:action:post") => {
            include_str!("../catalog/mailman/pt-BR/list:admin:action:post.txt")
        }
        ("pt-BR", "list:admin:action:subscribe") => {
            include_str!("../catalog/mailman/pt-BR/list:admin:action:subscribe.txt")
        }
        ("pt-BR", "list:admin:action:unsubscribe") => {
            include_str!("../catalog/mailman/pt-BR/list:admin:action:unsubscribe.txt")
        }
        ("pt-BR", "list:admin:notice:pending") => {
            include_str!("../catalog/mailman/pt-BR/list:admin:notice:pending.txt")
        }
        ("pt-BR", "list:admin:notice:removal") => {
            include_str!("../catalog/mailman/pt-BR/list:admin:notice:removal.txt")
        }
        ("pt-BR", "list:admin:notice:subscribe") => {
            include_str!("../catalog/mailman/pt-BR/list:admin:notice:subscribe.txt")
        }
        ("pt-BR", "list:admin:notice:unrecognized") => {
            include_str!("../catalog/mailman/pt-BR/list:admin:notice:unrecognized.txt")
        }
        ("pt-BR", "list:admin:notice:unsubscribe") => {
            include_str!("../catalog/mailman/pt-BR/list:admin:notice:unsubscribe.txt")
        }
        ("pt-BR", "list:member:digest:masthead") => {
            include_str!("../catalog/mailman/pt-BR/list:member:digest:masthead.txt")
        }
        ("pt-BR", "list:member:generic:footer") => {
            include_str!("../catalog/mailman/pt-BR/list:member:generic:footer.txt")
        }
        ("pt-BR", "list:user:notice:hold") => {
            include_str!("../catalog/mailman/pt-BR/list:user:notice:hold.txt")
        }
        ("pt-BR", "list:user:notice:no-more-today") => {
            include_str!("../catalog/mailman/pt-BR/list:user:notice:no-more-today.txt")
        }
        ("pt-BR", "list:user:notice:post") => {
            include_str!("../catalog/mailman/pt-BR/list:user:notice:post.txt")
        }
        ("pt-BR", "list:user:notice:refuse") => {
            include_str!("../catalog/mailman/pt-BR/list:user:notice:refuse.txt")
        }
        ("ru", "domain:admin:notice:new-list") => {
            include_str!("../catalog/mailman/ru/domain:admin:notice:new-list.txt")
        }
        ("ru", "list:admin:action:post") => {
            include_str!("../catalog/mailman/ru/list:admin:action:post.txt")
        }
        ("ru", "list:admin:action:subscribe") => {
            include_str!("../catalog/mailman/ru/list:admin:action:subscribe.txt")
        }
        ("ru", "list:admin:action:unsubscribe") => {
            include_str!("../catalog/mailman/ru/list:admin:action:unsubscribe.txt")
        }
        ("ru", "list:admin:notice:pending") => {
            include_str!("../catalog/mailman/ru/list:admin:notice:pending.txt")
        }
        ("ru", "list:admin:notice:removal") => {
            include_str!("../catalog/mailman/ru/list:admin:notice:removal.txt")
        }
        ("ru", "list:admin:notice:subscribe") => {
            include_str!("../catalog/mailman/ru/list:admin:notice:subscribe.txt")
        }
        ("ru", "list:admin:notice:unrecognized") => {
            include_str!("../catalog/mailman/ru/list:admin:notice:unrecognized.txt")
        }
        ("ru", "list:admin:notice:unsubscribe") => {
            include_str!("../catalog/mailman/ru/list:admin:notice:unsubscribe.txt")
        }
        ("ru", "list:member:digest:masthead") => {
            include_str!("../catalog/mailman/ru/list:member:digest:masthead.txt")
        }
        ("ru", "list:member:generic:footer") => {
            include_str!("../catalog/mailman/ru/list:member:generic:footer.txt")
        }
        ("ru", "list:user:notice:hold") => {
            include_str!("../catalog/mailman/ru/list:user:notice:hold.txt")
        }
        ("ru", "list:user:notice:no-more-today") => {
            include_str!("../catalog/mailman/ru/list:user:notice:no-more-today.txt")
        }
        ("ru", "list:user:notice:post") => {
            include_str!("../catalog/mailman/ru/list:user:notice:post.txt")
        }
        ("ru", "list:user:notice:refuse") => {
            include_str!("../catalog/mailman/ru/list:user:notice:refuse.txt")
        }
        ("sk", "domain:admin:notice:new-list") => {
            include_str!("../catalog/mailman/sk/domain:admin:notice:new-list.txt")
        }
        ("sk", "list:admin:action:post") => {
            include_str!("../catalog/mailman/sk/list:admin:action:post.txt")
        }
        ("sk", "list:admin:action:subscribe") => {
            include_str!("../catalog/mailman/sk/list:admin:action:subscribe.txt")
        }
        ("sk", "list:admin:action:unsubscribe") => {
            include_str!("../catalog/mailman/sk/list:admin:action:unsubscribe.txt")
        }
        ("sk", "list:admin:notice:removal") => {
            include_str!("../catalog/mailman/sk/list:admin:notice:removal.txt")
        }
        ("sk", "list:admin:notice:subscribe") => {
            include_str!("../catalog/mailman/sk/list:admin:notice:subscribe.txt")
        }
        ("sk", "list:admin:notice:unrecognized") => {
            include_str!("../catalog/mailman/sk/list:admin:notice:unrecognized.txt")
        }
        ("sk", "list:admin:notice:unsubscribe") => {
            include_str!("../catalog/mailman/sk/list:admin:notice:unsubscribe.txt")
        }
        ("sk", "list:member:digest:masthead") => {
            include_str!("../catalog/mailman/sk/list:member:digest:masthead.txt")
        }
        ("sk", "list:member:generic:footer") => {
            include_str!("../catalog/mailman/sk/list:member:generic:footer.txt")
        }
        ("sk", "list:user:notice:hold") => {
            include_str!("../catalog/mailman/sk/list:user:notice:hold.txt")
        }
        ("sk", "list:user:notice:no-more-today") => {
            include_str!("../catalog/mailman/sk/list:user:notice:no-more-today.txt")
        }
        ("sk", "list:user:notice:post") => {
            include_str!("../catalog/mailman/sk/list:user:notice:post.txt")
        }
        ("sk", "list:user:notice:refuse") => {
            include_str!("../catalog/mailman/sk/list:user:notice:refuse.txt")
        }
        ("tr", "domain:admin:notice:new-list") => {
            include_str!("../catalog/mailman/tr/domain:admin:notice:new-list.txt")
        }
        ("tr", "list:admin:action:post") => {
            include_str!("../catalog/mailman/tr/list:admin:action:post.txt")
        }
        ("tr", "list:admin:action:subscribe") => {
            include_str!("../catalog/mailman/tr/list:admin:action:subscribe.txt")
        }
        ("tr", "list:admin:action:unsubscribe") => {
            include_str!("../catalog/mailman/tr/list:admin:action:unsubscribe.txt")
        }
        ("tr", "list:admin:notice:pending") => {
            include_str!("../catalog/mailman/tr/list:admin:notice:pending.txt")
        }
        ("tr", "list:admin:notice:removal") => {
            include_str!("../catalog/mailman/tr/list:admin:notice:removal.txt")
        }
        ("tr", "list:admin:notice:subscribe") => {
            include_str!("../catalog/mailman/tr/list:admin:notice:subscribe.txt")
        }
        ("tr", "list:admin:notice:unrecognized") => {
            include_str!("../catalog/mailman/tr/list:admin:notice:unrecognized.txt")
        }
        ("tr", "list:admin:notice:unsubscribe") => {
            include_str!("../catalog/mailman/tr/list:admin:notice:unsubscribe.txt")
        }
        ("tr", "list:member:digest:masthead") => {
            include_str!("../catalog/mailman/tr/list:member:digest:masthead.txt")
        }
        ("tr", "list:member:generic:footer") => {
            include_str!("../catalog/mailman/tr/list:member:generic:footer.txt")
        }
        ("tr", "list:user:notice:hold") => {
            include_str!("../catalog/mailman/tr/list:user:notice:hold.txt")
        }
        ("tr", "list:user:notice:no-more-today") => {
            include_str!("../catalog/mailman/tr/list:user:notice:no-more-today.txt")
        }
        ("tr", "list:user:notice:post") => {
            include_str!("../catalog/mailman/tr/list:user:notice:post.txt")
        }
        ("tr", "list:user:notice:refuse") => {
            include_str!("../catalog/mailman/tr/list:user:notice:refuse.txt")
        }
        ("uk", "domain:admin:notice:new-list") => {
            include_str!("../catalog/mailman/uk/domain:admin:notice:new-list.txt")
        }
        ("uk", "list:admin:action:post") => {
            include_str!("../catalog/mailman/uk/list:admin:action:post.txt")
        }
        ("uk", "list:admin:action:subscribe") => {
            include_str!("../catalog/mailman/uk/list:admin:action:subscribe.txt")
        }
        ("uk", "list:admin:action:unsubscribe") => {
            include_str!("../catalog/mailman/uk/list:admin:action:unsubscribe.txt")
        }
        ("uk", "list:admin:notice:pending") => {
            include_str!("../catalog/mailman/uk/list:admin:notice:pending.txt")
        }
        ("uk", "list:admin:notice:removal") => {
            include_str!("../catalog/mailman/uk/list:admin:notice:removal.txt")
        }
        ("uk", "list:admin:notice:subscribe") => {
            include_str!("../catalog/mailman/uk/list:admin:notice:subscribe.txt")
        }
        ("uk", "list:admin:notice:unrecognized") => {
            include_str!("../catalog/mailman/uk/list:admin:notice:unrecognized.txt")
        }
        ("uk", "list:admin:notice:unsubscribe") => {
            include_str!("../catalog/mailman/uk/list:admin:notice:unsubscribe.txt")
        }
        ("uk", "list:member:digest:masthead") => {
            include_str!("../catalog/mailman/uk/list:member:digest:masthead.txt")
        }
        ("uk", "list:member:generic:footer") => {
            include_str!("../catalog/mailman/uk/list:member:generic:footer.txt")
        }
        ("uk", "list:user:notice:hold") => {
            include_str!("../catalog/mailman/uk/list:user:notice:hold.txt")
        }
        ("uk", "list:user:notice:no-more-today") => {
            include_str!("../catalog/mailman/uk/list:user:notice:no-more-today.txt")
        }
        ("uk", "list:user:notice:post") => {
            include_str!("../catalog/mailman/uk/list:user:notice:post.txt")
        }
        ("uk", "list:user:notice:refuse") => {
            include_str!("../catalog/mailman/uk/list:user:notice:refuse.txt")
        }
        ("zh-Hans", "domain:admin:notice:new-list") => {
            include_str!("../catalog/mailman/zh-Hans/domain:admin:notice:new-list.txt")
        }
        ("zh-Hans", "list:admin:action:post") => {
            include_str!("../catalog/mailman/zh-Hans/list:admin:action:post.txt")
        }
        ("zh-Hans", "list:admin:action:subscribe") => {
            include_str!("../catalog/mailman/zh-Hans/list:admin:action:subscribe.txt")
        }
        ("zh-Hans", "list:admin:action:unsubscribe") => {
            include_str!("../catalog/mailman/zh-Hans/list:admin:action:unsubscribe.txt")
        }
        ("zh-Hans", "list:admin:notice:pending") => {
            include_str!("../catalog/mailman/zh-Hans/list:admin:notice:pending.txt")
        }
        ("zh-Hans", "list:admin:notice:removal") => {
            include_str!("../catalog/mailman/zh-Hans/list:admin:notice:removal.txt")
        }
        ("zh-Hans", "list:admin:notice:subscribe") => {
            include_str!("../catalog/mailman/zh-Hans/list:admin:notice:subscribe.txt")
        }
        ("zh-Hans", "list:admin:notice:unrecognized") => {
            include_str!("../catalog/mailman/zh-Hans/list:admin:notice:unrecognized.txt")
        }
        ("zh-Hans", "list:admin:notice:unsubscribe") => {
            include_str!("../catalog/mailman/zh-Hans/list:admin:notice:unsubscribe.txt")
        }
        ("zh-Hans", "list:member:digest:masthead") => {
            include_str!("../catalog/mailman/zh-Hans/list:member:digest:masthead.txt")
        }
        ("zh-Hans", "list:member:generic:footer") => {
            include_str!("../catalog/mailman/zh-Hans/list:member:generic:footer.txt")
        }
        ("zh-Hans", "list:user:notice:hold") => {
            include_str!("../catalog/mailman/zh-Hans/list:user:notice:hold.txt")
        }
        ("zh-Hans", "list:user:notice:no-more-today") => {
            include_str!("../catalog/mailman/zh-Hans/list:user:notice:no-more-today.txt")
        }
        ("zh-Hans", "list:user:notice:post") => {
            include_str!("../catalog/mailman/zh-Hans/list:user:notice:post.txt")
        }
        ("zh-Hans", "list:user:notice:refuse") => {
            include_str!("../catalog/mailman/zh-Hans/list:user:notice:refuse.txt")
        }
        _ => return None,
    })
}
