[package]
name = "listmngr-api"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
flate2.workspace = true
futures.workspace = true
askama.workspace = true
listmngr-archive = { path = "../archive", version = "0.1.0" }
axum = { workspace = true, features = ["multipart"] }
base64.workspace = true
chrono.workspace = true
bytes.workspace = true
dashmap.workspace = true
http.workspace = true
ipnet.workspace = true
listmngr-i18n = { path = "../i18n", version = "0.1.0" }
listmngr-web = { path = "../web", version = "0.1.0" }
listmngr-core = { path = "../core", version = "0.1.0" }
listmngr-db = { path = "../db", version = "0.1.0" }
listmngr-mail = { path = "../mail", version = "0.1.0" }
listmngr-pipeline = { path = "../pipeline", version = "0.1.0" }
p256.workspace = true
rand.workspace = true
reqwest = { workspace = true, features = ["rustls-tls-webpki-roots"] }
rsa.workspace = true
subtle.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true
sha2.workspace = true
sqlx = { workspace = true, features = ["any"] }
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
utoipa.workspace = true
uuid.workspace = true

[dev-dependencies]
ciborium.workspace = true
reqwest.workspace = true
oas3 = "0.22.0"
prometheus-parse = "0.2.5"
tempfile = "=3.27.0"
tower.workspace = true
