#!/usr/bin/env python3
"""Generate the configuration reference of the book from the `config_struct!`
blocks in crates/core/src/lib.rs: every section, every key, its type, its
default and the comment above it. `--check` fails when the committed page
differs from what the source says; `--output <file>` names another page.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "crates/core/src/lib.rs"
DEFAULT_OUTPUT = ROOT / "docs/book/src/configuration-reference.md"

BLOCK = re.compile(r"config_struct!\((\w+)\s*\{(.*?)\n?\}\);", re.S)


def split_fields(body: str):
    """Fields separated by commas at depth zero; `//` comments kept as the
    description of the field that follows them."""
    fields, current, depth, in_str, comment = [], [], 0, False, []
    i = 0
    lines = body.split("\n")
    text_lines = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("//"):
            comment.append(stripped.lstrip("/").strip())
            continue
        text_lines.append((line, " ".join(comment)))
        if stripped:
            comment = []
    buffer, desc, pending_desc = "", "", ""
    for line, line_desc in text_lines:
        if not buffer.strip() and line_desc:
            pending_desc = line_desc
        for ch in line:
            if ch == '"' and not buffer.endswith("\\"):
                in_str = not in_str
            if not in_str:
                if ch in "([{":
                    depth += 1
                elif ch in ")]}":
                    depth -= 1
                elif ch == "," and depth == 0:
                    if buffer.strip():
                        fields.append((buffer.strip(), pending_desc))
                    buffer, pending_desc = "", ""
                    continue
            buffer += ch
        buffer += " "
    if buffer.strip():
        fields.append((buffer.strip(), pending_desc))
    return fields


def parse():
    source = SOURCE.read_text()
    structs = {}
    for name, body in BLOCK.findall(source):
        entries = []
        for field, desc in split_fields(body):
            m = re.match(r"(\w+)\s*:\s*(.+?)\s*=\s*(.+)$", field, re.S)
            if not m:
                continue
            key, ty, default = m.group(1), " ".join(m.group(2).split()), " ".join(m.group(3).split())
            entries.append((key, ty, default, desc))
        structs[name] = entries
    # The top-level sections: `pub <section>: <Struct>,` inside `pub struct Config`.
    config = re.search(r"pub struct Config \{(.*?)\n\}", source, re.S).group(1)
    sections = re.findall(r"pub (\w+): (\w+Config)", config)
    return structs, sections


def pretty_default(default: str) -> str:
    d = default.strip()
    d = re.sub(r'^"(.*)"\.into\(\)$', r'"\1"', d)
    d = re.sub(r"^String::new\(\)$", '""', d)
    d = re.sub(r"^Vec::new\(\)$", "[]", d)
    d = re.sub(r"^(\w+Config)::default\(\)$", r"(see [\1])", d)
    d = re.sub(r"\.into\(\)", "", d)
    d = d.replace("vec![", "[")
    return d


def render(structs, sections) -> str:
    out = ["# Configuration reference", "",
           "Generated by `scripts/config-reference.py` from `crates/core/src/lib.rs`; do not edit by hand.",
           "Every key is set in `listmngr.toml` under its section, or as the environment variable",
           "`LISTMNGR__<SECTION>__<KEY>` (upper case, sections joined by `__`). `listmngr conf` prints",
           "the effective values with secrets redacted; `listmngr conf --key section.key` prints one.", ""]
    seen = set()

    def section(path, struct):
        if struct in seen or struct not in structs:
            return
        seen.add(struct)
        out.append(f"## `[{path}]`")
        out.append("")
        out.append("| Key | Type | Default | Notes |")
        out.append("| --- | --- | --- | --- |")
        nested = []
        for key, ty, default, desc in structs[struct]:
            m = re.match(r"(\w+Config)$", ty)
            if m:
                nested.append((f"{path}.{key}", m.group(1)))
                out.append(f"| `{key}` | section | — | see `[{path}.{key}]` |")
                continue
            out.append(f"| `{key}` | `{ty}` | `{pretty_default(default)}` | {desc} |")
        out.append("")
        for sub_path, sub_struct in nested:
            section(sub_path, sub_struct)

    for name, struct in sections:
        section(name, struct)
    return "\n".join(out) + "\n"


def main() -> int:
    args = sys.argv[1:]
    output = Path(args[args.index("--output") + 1]) if "--output" in args else DEFAULT_OUTPUT
    structs, sections = parse()
    text = render(structs, sections)
    if "--check" in args:
        current = output.read_text() if output.exists() else ""
        if current != text:
            print(f"{output} is out of date; run scripts/config-reference.py", file=sys.stderr)
            return 1
        print("configuration reference: in sync")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text)
    print(f"wrote {output} ({len(structs)} structs, {len(sections)} sections)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
