[package]
name = "listmngr-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
zeroize = "=1.9.0"
regex.workspace = true
chrono.workspace = true
hmac = "0.12.1"
sha2.workspace = true
rand.workspace = true
base64.workspace = true
figment.workspace = true
idna.workspace = true
ipnet.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
utoipa.workspace = true
uuid.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "=0.2.189"

[dev-dependencies]
tempfile = "3.23.0"
